# _config.yml

title: ronynn blog
description: "A minimal blog with multiple themes and a Vanta.js dots background."
baseurl: "/blog"               


url: "https://ronynn.github.io"  


markdown: kramdown
theme: minima   


paginate: 5
paginate_path: "/page:num"
plugins:
  - jekyll-feed
  
include:
  - _pages


# Custom Variables
default_theme: "gruvbox"   # Set to one of: gruvbox, monokai, dracula, nord, solarized, catppuccin, tokyo-night, everforest